/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubjectsRouteImport } from './routes/subjects'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SpacedRevisionRouteImport } from './routes/spaced-revision'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as QuizModesRouteImport } from './routes/quiz-modes'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NewRouteImport } from './routes/new'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DebugRouteImport } from './routes/debug'
import { Route as AddTopicRouteImport } from './routes/add-topic'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubjectIdRouteImport } from './routes/subject.$id'
import { Route as ResultIdRouteImport } from './routes/result.$id'
import { Route as QuizIdRouteImport } from './routes/quiz.$id'
import { Route as TopicTopicIdNotesRouteImport } from './routes/topic.$topicId.notes'
import { Route as SubjectIdAddTopicRouteImport } from './routes/subject.$id.add-topic'

const SubjectsRoute = SubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacedRevisionRoute = SpacedRevisionRouteImport.update({
  id: '/spaced-revision',
  path: '/spaced-revision',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizModesRoute = QuizModesRouteImport.update({
  id: '/quiz-modes',
  path: '/quiz-modes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugRoute = DebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const AddTopicRoute = AddTopicRouteImport.update({
  id: '/add-topic',
  path: '/add-topic',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectIdRoute = SubjectIdRouteImport.update({
  id: '/subject/$id',
  path: '/subject/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultIdRoute = ResultIdRouteImport.update({
  id: '/result/$id',
  path: '/result/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizIdRoute = QuizIdRouteImport.update({
  id: '/quiz/$id',
  path: '/quiz/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicTopicIdNotesRoute = TopicTopicIdNotesRouteImport.update({
  id: '/topic/$topicId/notes',
  path: '/topic/$topicId/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectIdAddTopicRoute = SubjectIdAddTopicRouteImport.update({
  id: '/add-topic',
  path: '/add-topic',
  getParentRoute: () => SubjectIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-topic': typeof AddTopicRoute
  '/debug': typeof DebugRoute
  '/gallery': typeof GalleryRoute
  '/new': typeof NewRoute
  '/profile': typeof ProfileRoute
  '/quiz-modes': typeof QuizModesRoute
  '/rewards': typeof RewardsRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/spaced-revision': typeof SpacedRevisionRoute
  '/stats': typeof StatsRoute
  '/subjects': typeof SubjectsRoute
  '/quiz/$id': typeof QuizIdRoute
  '/result/$id': typeof ResultIdRoute
  '/subject/$id': typeof SubjectIdRouteWithChildren
  '/subject/$id/add-topic': typeof SubjectIdAddTopicRoute
  '/topic/$topicId/notes': typeof TopicTopicIdNotesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-topic': typeof AddTopicRoute
  '/debug': typeof DebugRoute
  '/gallery': typeof GalleryRoute
  '/new': typeof NewRoute
  '/profile': typeof ProfileRoute
  '/quiz-modes': typeof QuizModesRoute
  '/rewards': typeof RewardsRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/spaced-revision': typeof SpacedRevisionRoute
  '/stats': typeof StatsRoute
  '/subjects': typeof SubjectsRoute
  '/quiz/$id': typeof QuizIdRoute
  '/result/$id': typeof ResultIdRoute
  '/subject/$id': typeof SubjectIdRouteWithChildren
  '/subject/$id/add-topic': typeof SubjectIdAddTopicRoute
  '/topic/$topicId/notes': typeof TopicTopicIdNotesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-topic': typeof AddTopicRoute
  '/debug': typeof DebugRoute
  '/gallery': typeof GalleryRoute
  '/new': typeof NewRoute
  '/profile': typeof ProfileRoute
  '/quiz-modes': typeof QuizModesRoute
  '/rewards': typeof RewardsRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/spaced-revision': typeof SpacedRevisionRoute
  '/stats': typeof StatsRoute
  '/subjects': typeof SubjectsRoute
  '/quiz/$id': typeof QuizIdRoute
  '/result/$id': typeof ResultIdRoute
  '/subject/$id': typeof SubjectIdRouteWithChildren
  '/subject/$id/add-topic': typeof SubjectIdAddTopicRoute
  '/topic/$topicId/notes': typeof TopicTopicIdNotesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-topic'
    | '/debug'
    | '/gallery'
    | '/new'
    | '/profile'
    | '/quiz-modes'
    | '/rewards'
    | '/saved'
    | '/settings'
    | '/spaced-revision'
    | '/stats'
    | '/subjects'
    | '/quiz/$id'
    | '/result/$id'
    | '/subject/$id'
    | '/subject/$id/add-topic'
    | '/topic/$topicId/notes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-topic'
    | '/debug'
    | '/gallery'
    | '/new'
    | '/profile'
    | '/quiz-modes'
    | '/rewards'
    | '/saved'
    | '/settings'
    | '/spaced-revision'
    | '/stats'
    | '/subjects'
    | '/quiz/$id'
    | '/result/$id'
    | '/subject/$id'
    | '/subject/$id/add-topic'
    | '/topic/$topicId/notes'
  id:
    | '__root__'
    | '/'
    | '/add-topic'
    | '/debug'
    | '/gallery'
    | '/new'
    | '/profile'
    | '/quiz-modes'
    | '/rewards'
    | '/saved'
    | '/settings'
    | '/spaced-revision'
    | '/stats'
    | '/subjects'
    | '/quiz/$id'
    | '/result/$id'
    | '/subject/$id'
    | '/subject/$id/add-topic'
    | '/topic/$topicId/notes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddTopicRoute: typeof AddTopicRoute
  DebugRoute: typeof DebugRoute
  GalleryRoute: typeof GalleryRoute
  NewRoute: typeof NewRoute
  ProfileRoute: typeof ProfileRoute
  QuizModesRoute: typeof QuizModesRoute
  RewardsRoute: typeof RewardsRoute
  SavedRoute: typeof SavedRoute
  SettingsRoute: typeof SettingsRoute
  SpacedRevisionRoute: typeof SpacedRevisionRoute
  StatsRoute: typeof StatsRoute
  SubjectsRoute: typeof SubjectsRoute
  QuizIdRoute: typeof QuizIdRoute
  ResultIdRoute: typeof ResultIdRoute
  SubjectIdRoute: typeof SubjectIdRouteWithChildren
  TopicTopicIdNotesRoute: typeof TopicTopicIdNotesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subjects': {
      id: '/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof SubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaced-revision': {
      id: '/spaced-revision'
      path: '/spaced-revision'
      fullPath: '/spaced-revision'
      preLoaderRoute: typeof SpacedRevisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz-modes': {
      id: '/quiz-modes'
      path: '/quiz-modes'
      fullPath: '/quiz-modes'
      preLoaderRoute: typeof QuizModesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-topic': {
      id: '/add-topic'
      path: '/add-topic'
      fullPath: '/add-topic'
      preLoaderRoute: typeof AddTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subject/$id': {
      id: '/subject/$id'
      path: '/subject/$id'
      fullPath: '/subject/$id'
      preLoaderRoute: typeof SubjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/$id': {
      id: '/result/$id'
      path: '/result/$id'
      fullPath: '/result/$id'
      preLoaderRoute: typeof ResultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$id': {
      id: '/quiz/$id'
      path: '/quiz/$id'
      fullPath: '/quiz/$id'
      preLoaderRoute: typeof QuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topic/$topicId/notes': {
      id: '/topic/$topicId/notes'
      path: '/topic/$topicId/notes'
      fullPath: '/topic/$topicId/notes'
      preLoaderRoute: typeof TopicTopicIdNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subject/$id/add-topic': {
      id: '/subject/$id/add-topic'
      path: '/add-topic'
      fullPath: '/subject/$id/add-topic'
      preLoaderRoute: typeof SubjectIdAddTopicRouteImport
      parentRoute: typeof SubjectIdRoute
    }
  }
}

interface SubjectIdRouteChildren {
  SubjectIdAddTopicRoute: typeof SubjectIdAddTopicRoute
}

const SubjectIdRouteChildren: SubjectIdRouteChildren = {
  SubjectIdAddTopicRoute: SubjectIdAddTopicRoute,
}

const SubjectIdRouteWithChildren = SubjectIdRoute._addFileChildren(
  SubjectIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddTopicRoute: AddTopicRoute,
  DebugRoute: DebugRoute,
  GalleryRoute: GalleryRoute,
  NewRoute: NewRoute,
  ProfileRoute: ProfileRoute,
  QuizModesRoute: QuizModesRoute,
  RewardsRoute: RewardsRoute,
  SavedRoute: SavedRoute,
  SettingsRoute: SettingsRoute,
  SpacedRevisionRoute: SpacedRevisionRoute,
  StatsRoute: StatsRoute,
  SubjectsRoute: SubjectsRoute,
  QuizIdRoute: QuizIdRoute,
  ResultIdRoute: ResultIdRoute,
  SubjectIdRoute: SubjectIdRouteWithChildren,
  TopicTopicIdNotesRoute: TopicTopicIdNotesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
